test:
  runs-on: ubuntu-latest
  
  needs: build

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Run unit tests with Jest
      run: npm test
